apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auto-auction-ingress
  namespace: auto-auction
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - auto.2msi.org
    secretName: auto-auction-tls
  rules:
  - host: auto.2msi.org
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: auto-auction-api
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: auto-auction-web
            port:
              number: 80
