apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: auto-auction

resources:
- namespace.yaml
- secrets.yaml
- postgres/pvc.yaml
- postgres/deployment.yaml
- postgres/service.yaml
- api/deployment.yaml
- api/service.yaml
- web/deployment.yaml
- web/service.yaml
- scraper/cronjob.yaml
- ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: auto-auction
