apiVersion: v1
kind: Secret
metadata:
  name: auto-auction-secrets
  namespace: auto-auction
type: Opaque
stringData:
  # PostgreSQL credentials
  postgres-user: autoauction
  postgres-password: CHANGE_ME_IN_PRODUCTION
  postgres-db: autoauction
  database-url: postgres://autoauction:CHANGE_ME_IN_PRODUCTION@postgres:5432/autoauction?sslmode=disable
  # SMTP credentials (Mailu noreply account)
  smtp-host: mailu-postfix.mailu.svc.cluster.local
  smtp-port: "587"
  smtp-user: noreply@octol.ing
  smtp-password: UaYX5RnGbwicKxpxuu3gbIqk
  smtp-from: noreply@octol.ing
  app-base-url: https://auction.2msi.org
